# Generated by Django 3.2.9 on 2022-02-18 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eyestream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
