# Generated by Django 3.2.9 on 2022-02-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyestream', '0002_videos_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
