# Generated by Django 3.2.9 on 2022-03-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyestream', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
