# Generated by Django 3.2.9 on 2022-03-23 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eyestream', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='duration',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
